# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_service_pb2 as trading__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """============================================
    认证服务 - API Key 验证
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyApiKey = channel.unary_unary(
                '/trading.AuthService/VerifyApiKey',
                request_serializer=trading__service__pb2.VerifyApiKeyRequest.SerializeToString,
                response_deserializer=trading__service__pb2.VerifyApiKeyResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """============================================
    认证服务 - API Key 验证
    ============================================

    """

    def VerifyApiKey(self, request, context):
        """验证 API Key，返回关联的用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyApiKey,
                    request_deserializer=trading__service__pb2.VerifyApiKeyRequest.FromString,
                    response_serializer=trading__service__pb2.VerifyApiKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """============================================
    认证服务 - API Key 验证
    ============================================

    """

    @staticmethod
    def VerifyApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.AuthService/VerifyApiKey',
            trading__service__pb2.VerifyApiKeyRequest.SerializeToString,
            trading__service__pb2.VerifyApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DatabaseServiceStub(object):
    """============================================
    数据库服务 - 仓位跟单相关操作
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPositionTracking = channel.unary_unary(
                '/trading.DatabaseService/GetPositionTracking',
                request_serializer=trading__service__pb2.GetPositionTrackingRequest.SerializeToString,
                response_deserializer=trading__service__pb2.PositionTrackingResponse.FromString,
                _registered_method=True)
        self.GetActivePositionTrackings = channel.unary_unary(
                '/trading.DatabaseService/GetActivePositionTrackings',
                request_serializer=trading__service__pb2.GetActivePositionTrackingsRequest.SerializeToString,
                response_deserializer=trading__service__pb2.PositionTrackingListResponse.FromString,
                _registered_method=True)
        self.SavePositionTracking = channel.unary_unary(
                '/trading.DatabaseService/SavePositionTracking',
                request_serializer=trading__service__pb2.SavePositionTrackingRequest.SerializeToString,
                response_deserializer=trading__service__pb2.SavePositionTrackingResponse.FromString,
                _registered_method=True)
        self.UpdateTrackingStatus = channel.unary_unary(
                '/trading.DatabaseService/UpdateTrackingStatus',
                request_serializer=trading__service__pb2.UpdateTrackingStatusRequest.SerializeToString,
                response_deserializer=trading__service__pb2.UpdateTrackingResponse.FromString,
                _registered_method=True)
        self.UpdateTrackingPosition = channel.unary_unary(
                '/trading.DatabaseService/UpdateTrackingPosition',
                request_serializer=trading__service__pb2.UpdateTrackingPositionRequest.SerializeToString,
                response_deserializer=trading__service__pb2.UpdateTrackingResponse.FromString,
                _registered_method=True)
        self.GetEnabledCopyAddresses = channel.unary_unary(
                '/trading.DatabaseService/GetEnabledCopyAddresses',
                request_serializer=trading__service__pb2.GetEnabledCopyAddressesRequest.SerializeToString,
                response_deserializer=trading__service__pb2.CopyAddressListResponse.FromString,
                _registered_method=True)
        self.CheckPositionTrackingExists = channel.unary_unary(
                '/trading.DatabaseService/CheckPositionTrackingExists',
                request_serializer=trading__service__pb2.CheckPositionTrackingExistsRequest.SerializeToString,
                response_deserializer=trading__service__pb2.CheckPositionTrackingExistsResponse.FromString,
                _registered_method=True)
        self.ToggleCopyTradingAddress = channel.unary_unary(
                '/trading.DatabaseService/ToggleCopyTradingAddress',
                request_serializer=trading__service__pb2.ToggleCopyTradingAddressRequest.SerializeToString,
                response_deserializer=trading__service__pb2.UpdateTrackingResponse.FromString,
                _registered_method=True)
        self.GetEnabledAddressTrackings = channel.unary_unary(
                '/trading.DatabaseService/GetEnabledAddressTrackings',
                request_serializer=trading__service__pb2.GetEnabledAddressTrackingsRequest.SerializeToString,
                response_deserializer=trading__service__pb2.AddressTrackingListResponse.FromString,
                _registered_method=True)


class DatabaseServiceServicer(object):
    """============================================
    数据库服务 - 仓位跟单相关操作
    ============================================

    """

    def GetPositionTracking(self, request, context):
        """获取单个仓位跟单详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivePositionTrackings(self, request, context):
        """获取所有活跃的仓位跟单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SavePositionTracking(self, request, context):
        """保存仓位跟单记录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTrackingStatus(self, request, context):
        """更新跟单状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTrackingPosition(self, request, context):
        """更新跟单仓位信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnabledCopyAddresses(self, request, context):
        """获取启用的跟单地址配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPositionTrackingExists(self, request, context):
        """检查仓位跟单是否存在
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleCopyTradingAddress(self, request, context):
        """启用/禁用跟单地址
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnabledAddressTrackings(self, request, context):
        """获取启用的地址跟踪配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPositionTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositionTracking,
                    request_deserializer=trading__service__pb2.GetPositionTrackingRequest.FromString,
                    response_serializer=trading__service__pb2.PositionTrackingResponse.SerializeToString,
            ),
            'GetActivePositionTrackings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivePositionTrackings,
                    request_deserializer=trading__service__pb2.GetActivePositionTrackingsRequest.FromString,
                    response_serializer=trading__service__pb2.PositionTrackingListResponse.SerializeToString,
            ),
            'SavePositionTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePositionTracking,
                    request_deserializer=trading__service__pb2.SavePositionTrackingRequest.FromString,
                    response_serializer=trading__service__pb2.SavePositionTrackingResponse.SerializeToString,
            ),
            'UpdateTrackingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTrackingStatus,
                    request_deserializer=trading__service__pb2.UpdateTrackingStatusRequest.FromString,
                    response_serializer=trading__service__pb2.UpdateTrackingResponse.SerializeToString,
            ),
            'UpdateTrackingPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTrackingPosition,
                    request_deserializer=trading__service__pb2.UpdateTrackingPositionRequest.FromString,
                    response_serializer=trading__service__pb2.UpdateTrackingResponse.SerializeToString,
            ),
            'GetEnabledCopyAddresses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnabledCopyAddresses,
                    request_deserializer=trading__service__pb2.GetEnabledCopyAddressesRequest.FromString,
                    response_serializer=trading__service__pb2.CopyAddressListResponse.SerializeToString,
            ),
            'CheckPositionTrackingExists': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPositionTrackingExists,
                    request_deserializer=trading__service__pb2.CheckPositionTrackingExistsRequest.FromString,
                    response_serializer=trading__service__pb2.CheckPositionTrackingExistsResponse.SerializeToString,
            ),
            'ToggleCopyTradingAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleCopyTradingAddress,
                    request_deserializer=trading__service__pb2.ToggleCopyTradingAddressRequest.FromString,
                    response_serializer=trading__service__pb2.UpdateTrackingResponse.SerializeToString,
            ),
            'GetEnabledAddressTrackings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnabledAddressTrackings,
                    request_deserializer=trading__service__pb2.GetEnabledAddressTrackingsRequest.FromString,
                    response_serializer=trading__service__pb2.AddressTrackingListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.DatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """============================================
    数据库服务 - 仓位跟单相关操作
    ============================================

    """

    @staticmethod
    def GetPositionTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/GetPositionTracking',
            trading__service__pb2.GetPositionTrackingRequest.SerializeToString,
            trading__service__pb2.PositionTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivePositionTrackings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/GetActivePositionTrackings',
            trading__service__pb2.GetActivePositionTrackingsRequest.SerializeToString,
            trading__service__pb2.PositionTrackingListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SavePositionTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/SavePositionTracking',
            trading__service__pb2.SavePositionTrackingRequest.SerializeToString,
            trading__service__pb2.SavePositionTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTrackingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/UpdateTrackingStatus',
            trading__service__pb2.UpdateTrackingStatusRequest.SerializeToString,
            trading__service__pb2.UpdateTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTrackingPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/UpdateTrackingPosition',
            trading__service__pb2.UpdateTrackingPositionRequest.SerializeToString,
            trading__service__pb2.UpdateTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnabledCopyAddresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/GetEnabledCopyAddresses',
            trading__service__pb2.GetEnabledCopyAddressesRequest.SerializeToString,
            trading__service__pb2.CopyAddressListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPositionTrackingExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/CheckPositionTrackingExists',
            trading__service__pb2.CheckPositionTrackingExistsRequest.SerializeToString,
            trading__service__pb2.CheckPositionTrackingExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleCopyTradingAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/ToggleCopyTradingAddress',
            trading__service__pb2.ToggleCopyTradingAddressRequest.SerializeToString,
            trading__service__pb2.UpdateTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnabledAddressTrackings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.DatabaseService/GetEnabledAddressTrackings',
            trading__service__pb2.GetEnabledAddressTrackingsRequest.SerializeToString,
            trading__service__pb2.AddressTrackingListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RedisServiceStub(object):
    """============================================
    Redis服务 - Pub/Sub和缓存操作
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/trading.RedisService/Publish',
                request_serializer=trading__service__pb2.PublishRequest.SerializeToString,
                response_deserializer=trading__service__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/trading.RedisService/Subscribe',
                request_serializer=trading__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=trading__service__pb2.SubscribeMessage.FromString,
                _registered_method=True)
        self.SetEx = channel.unary_unary(
                '/trading.RedisService/SetEx',
                request_serializer=trading__service__pb2.SetExRequest.SerializeToString,
                response_deserializer=trading__service__pb2.SetExResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/trading.RedisService/Get',
                request_serializer=trading__service__pb2.GetRequest.SerializeToString,
                response_deserializer=trading__service__pb2.GetResponse.FromString,
                _registered_method=True)


class RedisServiceServicer(object):
    """============================================
    Redis服务 - Pub/Sub和缓存操作
    ============================================

    """

    def Publish(self, request, context):
        """发布消息到指定channel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """订阅channel（服务端流）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEx(self, request, context):
        """设置带过期时间的键值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """获取键值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=trading__service__pb2.PublishRequest.FromString,
                    response_serializer=trading__service__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=trading__service__pb2.SubscribeRequest.FromString,
                    response_serializer=trading__service__pb2.SubscribeMessage.SerializeToString,
            ),
            'SetEx': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEx,
                    request_deserializer=trading__service__pb2.SetExRequest.FromString,
                    response_serializer=trading__service__pb2.SetExResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=trading__service__pb2.GetRequest.FromString,
                    response_serializer=trading__service__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.RedisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.RedisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RedisService(object):
    """============================================
    Redis服务 - Pub/Sub和缓存操作
    ============================================

    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.RedisService/Publish',
            trading__service__pb2.PublishRequest.SerializeToString,
            trading__service__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trading.RedisService/Subscribe',
            trading__service__pb2.SubscribeRequest.SerializeToString,
            trading__service__pb2.SubscribeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.RedisService/SetEx',
            trading__service__pb2.SetExRequest.SerializeToString,
            trading__service__pb2.SetExResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.RedisService/Get',
            trading__service__pb2.GetRequest.SerializeToString,
            trading__service__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
